### ISSUE TITLE
Loading tiddlers breaks dates

### ISSUE THREAD

**Issue by Mirodin** [fiatjaf/tiddlywiki-remotestorage#3] opened 2018-02-25 19:52 UTC
When I save a new tiddler there is a valid JSON object stored to my remote storage. So saving to RS is fine (see below). Also all Tiddlers created during the session are shown just fine in the "Recent" tab.

![image3](https://user-images.githubusercontent.com/2410346/36645784-251cf722-1a6e-11e8-8cfb-b93baa273985.png)

After a revisit there are no more Tiddlers in the "Recent" tab which is caused by them being not parsed correctly. When I open the "Info" tab for a Tiddler all dates (created, modified) are filled with `NaNNaNNaNNaNNaNNaNNaN`. When retrieving a tiddler via the console `$tw.wiki.getTiddler(title)` it returns the tiddler objects with invalid dates. So it seems like there might be an issue loading tiddlers from remoteStorage.

![image1](https://user-images.githubusercontent.com/2410346/36645747-b2fc9dd2-1a6d-11e8-941b-df2f8dbc0334.png)
![image2](https://user-images.githubusercontent.com/2410346/36645748-b31dc304-1a6d-11e8-97ea-c48727e714ac.png)

**Comment by fiatjaf** [comment] 2018-02-26 18:13
I'll take a look at this as soon as I get home (I've been away from home for the last 3 days) tomorrow, @Mirodin. Thank you again for your patience in filling these issues.

I think this may be related to some errors I'm seeing at https://groups.google.com/forum/#!topic/tiddlywikidev/G7AvIJNG2SY (wrote that before realizing they could be caused by cache errors arising from bugged date parsing).

**Comment by fiatjaf** [comment] 2018-02-27 20:05
Fixed on cee7b46ce910d8fdeee3c2fd3dc0cc7272f3afe5.

**Closed as completed by fiatjaf** 2018-02-27 20:05 UTC
