### ISSUE TITLE
Incorrect namespace

### ISSUE THREAD

**Issue by Mirodin** [fiatjaf/tiddlywiki-remotestorage#1] opened 2018-02-22 12:38 UTC
I tried the plugin as it seemed to be the ideal solution for my problem with too many wikis. However when I open a wiki via http, change the namespace and toggle private, the tiddlers get saved to my remoteStorage as expected. But after opening the wiki in a new browser (or clearing cache etc.) and logging in to the same account the tiddlers get not fetched.

I set the namespace and private switch to the same settings and reloaded the page which lead to the values still being there as expected (as they are stored in the browser). But the network console shows only requests to `<remoteStorageURL>/tiddlers` and not as one would expect to `<remoteStorageURL>/tiddlers/<namespace>`. So there can be no tiddlers to be fetched as there is no `_index_` file at that path.

**Comment by fiatjaf** [comment] 2018-02-22 18:24
Sorry about that, @Mirodin. There was a bug with the code that fetched the value for the namespace and privateness of the remoteStorage bucket, so I guess it sometimes is defaulting to `public` and `main`. That was fixed on f1e1ceb284f526462c898dd8ffc6638ddc9ab9a1 and the new plugin version is already on [`$:/plugins/fiatjaf/remoteStorage`](https://tiddly.alhur.es/#%24%3A%2Fplugins%2Ffiatjaf%2FremoteStorage).

What should happen now is: whenever you change these settings, the next tiddlers created or edited will be saved to the new bucket configuration, but the list of tiddlers of the new bucket will not be fetched, so you will not be able to view them. There's no way to work around this erratic behavior, so whenever you change the namespace/privateness, please refresh the page. After the refresh you'll be presented with the tiddlers from the just-specified bucket.

I don't know if that explanation makes sense. Please let me know.
Also, please reopen this if you feel the issue is not fixed at all.

If you want to recover lost stuff or cleanup your remoteStorage, please use https://inspektor.5apps.com/ (you can't edit, but you can view and delete stuff).

---

One quick observation: the calls to `<remoteStorageURL>/tiddlers` are normal, they're the continuous-polling part of the syncing process of the remoteStorage JavaScript library.

**Closed as completed** 2018-02-22 18:26 UTC
